name: Deploy to Staging

on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install Dependencies
        run: npm ci --legacy-peer-deps
        
      - name: Run Deployment Script
        run: ./deploy-staging.sh "Deploy staging via GitHub Action (${{ github.sha }})"
        env:
          VERCEL_DEPLOY_HOOK_URL: ${{ secrets.VERCEL_DEPLOY_HOOK_URL_STAGING }}

# Ensure old/redundant steps below this point are removed by the edit model.
# The following steps are replaced by the 'Run Deployment Script' step above:
#      - name: Build
#        run: npm run build
#      - name: Trigger Vercel Deployment Webhook
#        run: | ... curl ...
#      - name: Run Deployment Script (the duplicate one at the end)
#        run: ./deploy-staging.sh ... 