name: Deploy to Production

# This workflow deploys the main branch to production
# IMPORTANT: The main branch is the production branch
# All changes to production must go through the main branch

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install Dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
        
      # Direct webhook call instead of Vercel CLI for more reliable deployment
      - name: Trigger Vercel Production Deployment Webhook
        run: |
          echo "Triggering Vercel Production Deployment via Webhook..."
          curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_j18jOo7H76ge7XNlqQtNUCwqrIfe/M8sHj7yBFj
          echo "Production deployment triggered successfully!" 