name: Deploy to Staging

on:
  push:
    branches:
      - staging
      - master-r6p9cm0bf
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Run Deployment Script
        run: ./deploy-staging.sh "Deploy staging via GitHub Action (${{ github.sha }})"
        env:
          VERCEL_DEPLOY_HOOK_URL: ${{ secrets.VERCEL_DEPLOY_HOOK_URL_STAGING }} # Ensure this secret is set in GitHub repository settings 